POST http://127.0.0.1:8000/api/tasks HTTP/1.1
Content-Type: application/json

{
    "title": "apprendre à apprendre" 
}

# {
#     "title": "exemple avec plusieurs propriétés", 
#     "description": "si je voulais ajouter plusieurs champs"
# }
#
# il faudrait aussi penser à ajouter propriété dans TaskController S07E03